<?php

namespace AppBundle\Repository;

/**
 * AlcaldeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlcaldeRepository extends \Doctrine\ORM\EntityRepository
{
}
